### ISSUE TITLE
关于 JSX 表达式返回的 JSX.Element 的类型

### ISSUE THREAD

**Issue by joe-sky** [ymzuiku/aoife#1]
您好，觉得您这个库很有意思，让我受到了启发。我运行过本项目的示例代码，比如这样的场景：

```tsx
function App() {
  return (
    <div class="app">
      <h1>Hello World</h1>
    </div>
  );
}

// el 的类型是 any
const el = <App />;

document.body.append(el);
```

代码中`<App />`的返回结果是 any 类型而不是 dom 元素应有的类型，这个貌似应是难以避免，受限于 TS 对 JSX 类型的限制吧。其实我之前也有过将 JSX 当做语法糖，然后将其表达式返回值用作其它的用途，可是一直因类型问题无法解决而受到困扰。

不知道作者是如何考虑这点的呢,，想交流请教一下？如果有更好的处理办法，那么我觉得把 JSX 表达式直接用作生成其他目的的语法糖就会更加符合直觉而容易被人们所接受。非常感谢～

**Comment by joe-sky** [comment]
发现了一个类似的库，它的 JSX 类型定义似乎完整一些：https://github.com/heyheyhello/haptic/blob/main/publish/index.d.ts#L15

看来可能难以做到每个 JSX 表达式都返回具体的 dom 元素类型， 但是大范围的类型还是可以列举的。

**Comment by ymzuiku** [comment]
谢谢提供的建议，现阶段 JSX 返回的类型其实不重要，因为 JSX 最终都是嵌套在另一个JSX中
