### ISSUE TITLE
看着不错的样式，没有英文介绍和SSR支持？

### ISSUE THREAD

**Issue by sbfkcel** [ymzuiku/aoife#2]
如题

**Comment by ymzuiku** [comment]
您好，没有SSR支持, 如果有SSR需求，可以看看我另一个仓库：https://github.com/ymzuiku/create-react-ssx

**Comment by sbfkcel** [comment]
了解学习下。嘿嘿
你的 https://github.com/ymzuiku/create-react-ssx 跟 next.js 比较有啥特色呀？

**Comment by JGConsulting** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
wweic, @mattxlee, @newzubakhin, @kgantsov, @UnitylChaos, @evil-shrike, @jvff, @vibhas77, @pankajanand26, @palash25, @xchmwang, @delibash, @johnnyhsu, @nmarcetic, @yyh1102, @jdmarques, @utkarsh5k, @IndigoDai, @Awea, @Marveliu
